//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<int> VisitId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> ToothId { get; set; }
    
        public virtual Visit Visit { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Tooth Tooth { get; set; }
    }
}
