//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group()
        {
            this.SubGroups = new HashSet<SubGroup>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public Nullable<int> PriceListId { get; set; }
        public Nullable<decimal> LowerPrice { get; set; }
        public Nullable<decimal> UpperPrice { get; set; }
    
        public virtual PriceList PriceList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubGroup> SubGroups { get; set; }
    }
}
