//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinic.Data
{

    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PDContainer : DbContext
    {
        public PDContainer()
            : base("name=PDContainer")
        {
        }

        public PDContainer(string connectionString)
            : base(connectionString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Visit> Visits { get; set; }
        public virtual DbSet<Tooth> Teeth { get; set; }
        public virtual DbSet<Treatment> Treatments { get; set; }
        public virtual DbSet<SubTreatment> SubTreatments { get; set; }
        public virtual DbSet<Sub2Treatment> Sub2Treatments { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Office> Offices { get; set; }
        public virtual DbSet<PriceList> PriceLists { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<SubGroup> SubGroups { get; set; }
        public virtual DbSet<Sub2Group> Sub2Groups { get; set; }
    }
}
