//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinic.Data
{
    using System;

    public partial class Sub2Treatment
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public Nullable<int> SubTreatmentId { get; set; }
    
        public virtual SubTreatment SubTreatment { get; set; }
    }
}
