//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sub2Group
    {
        public int Id { get; set; }
        public Nullable<int> SubGroupId { get; set; }
        public Nullable<decimal> LowerPrice { get; set; }
        public Nullable<decimal> UpperPrice { get; set; }
        public string Name { get; set; }
    
        public virtual SubGroup SubGroup { get; set; }
    }
}
