//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinic.Data
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class Visit
    {
        public Visit()
        {
            this.Comments = new List<Comment>();
            this.Treatments = new List<Treatment>();
            this.Teeth = new List<Tooth>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int EmployeeId { get; set; }
        public int PatientId { get; set; }
        public int OfficeId { get; set; }
    
        public virtual Employee Employee { get; set; }

        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Office Office { get; set; }

        public virtual ICollection<Treatment> Treatments { get; set; }

        public virtual ICollection<Tooth> Teeth { get; set; }

        [NotMapped]
        public bool filled
        {
            get { return this.Treatments.Any() | this.Comments.Any() | this.Teeth.Any(); }
            set { filled = value; }
        }
        public static Visit Empty => new Visit();
    }
}
